name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  REGION: us-central1 
  SERVICE: weather-app

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate with Google Cloud using service account key
    - name: Authenticate with Google Cloud
      run: echo '${{ secrets.GCP_AUTH }}' > /tmp/gcp_key.json

    # Build and push image to Google Container Registry
    - name: Build
      run: |
        gcloud builds submit \
          --quiet \
          --project "${{ secrets.RUN_PROJECT }}" \
          --tag "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA"
          
    # Deploy image to Cloud Run
    - name: Deploy
      run: |
        gcloud run deploy "$SERVICE" \
          --quiet \
          --region "$REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
