name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.WEATHER_ID }}
  SERVICE: weather-app 
  REGION: us-central1 

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        # Debugging output: Print the value of PROJECT_ID variable
    - name: Debug
      run: |
        echo "Project ID: $PROJECT_ID"
    # Setup gcloud CLI
    - uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 416.0.0'
        service_account_key: ${{ secrets.WEATHER_RUN_KEY }}
        project_id: ${{ secrets.WEATHER_ID }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA"
          
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE" \
          --quiet \
          --region "$REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
